test/uk/gov/hmrc/residencenilratebandcalculator/HelloWorldControllerSpec.scala

Remove tests until we can work out how to DI MassagesApi

RNRBC-40: Remove tests until we can work out how to DI MassagesApi

---

app/uk/gov/hmrc/residencenilratebandcalculator/controllers/GrossEstateValueController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/filters/Filters.scala
app/uk/gov/hmrc/residencenilratebandcalculator/filters/SessionId.scala

Create filter to add sessionId

RNRBC-44: Create filter to add sessionId

---

app/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnector.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/CalculationResult.scala
test/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnectorSpec.scala

RNRBC-61: Implement RnrbConnector.send

---

app/uk/gov/hmrc/residencenilratebandcalculator/JsonBuilder.scala
app/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnector.scala
test/uk/gov/hmrc/residencenilratebandcalculator/JsonBuilderSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnectorSpec.scala

Request the schema from the microservice

Rnrbc 74: Request the schema from the microservice

---

app/uk/gov/hmrc/residencenilratebandcalculator/models/CalculationResult.scala
app/uk/gov/hmrc/residencenilratebandcalculator/views/results.scala.html
conf/messages
test/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnectorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ResultsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ResultsViewSpec.scala

RNRBC-57 - Add carry forward and applicable nil rate band amounts to results

---

app/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnector.scala

Point to the new schemas location

RNRBC-RAML: Point to the new schemas location

---

app/uk/gov/hmrc/residencenilratebandcalculator/Constants.scala
app/uk/gov/hmrc/residencenilratebandcalculator/Navigator.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyAssetsPassingToDirectDescendantsController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyBroughtForwardAllowanceOnDisposalController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AssetsPassingToDirectDescendantsController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/BroughtForwardAllowanceOnDisposalController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueOfDisposedPropertyController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/views/any_assets_passing_to_direct_descendants.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/any_brought_forward_allowance_on_disposal.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/assets_passing_to_direct_descendants.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/brought_forward_allowance_on_disposal.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/value_of_disposed_property.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/residencenilratebandcalculator/NavigatorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyAssetsPassingToDirectDescendantsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyBroughtForwardAllowanceOnDisposalControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AssetsPassingToDirectDescendantsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/BroughtForwardAllowanceOnDisposalControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueOfDisposedPropertyControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/AnyAssetsPassingToDirectDescendantsViewSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/AnyBroughtForwardAllowanceOnDisposalViewSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/AssetsPassingToDirectDescendantsViewSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/BroughtForwardAllowanceOnDisposalViewSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ValueOfDisposedPropertyViewSpec.scala

Note that we are not yet passing the downsizing details to the microservice calculation, that will be handled in a separate PR.

RNRBC-102 to 106: Additional downsizing page

---

app/uk/gov/hmrc/residencenilratebandcalculator/Constants.scala
app/uk/gov/hmrc/residencenilratebandcalculator/Navigator.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/CheckAnswersController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/AnswerRow.scala
app/uk/gov/hmrc/residencenilratebandcalculator/views/check_answers.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/rnrbHelpers/rows.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/residencenilratebandcalculator/NavigatorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/CheckAnswersControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/AnswerRowSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/CheckAnswersViewSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/rnrbHelpers/RowsViewSpec.scala

RNRBC-96: Add check your answers page

---

test/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnectorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyAssetsPassingToDirectDescendantsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyBroughtForwardAllowanceControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyBroughtForwardAllowanceOnDisposalControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyDownsizingAllowanceControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyExemptionControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AssetsPassingToDirectDescendantsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/BroughtForwardAllowanceControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/BroughtForwardAllowanceOnDisposalControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ChargeableTransferAmountControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/DateControllerSpecBase.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/DateOfDeathControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/DateOfDisposalControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/EstateHasPropertyControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/GrossEstateValueControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/PercentageCloselyInheritedControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/PropertyValueControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/SimpleControllerSpecBase.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueOfDisposedPropertyControllerSpec.scala

FIX-PENDING-TESTS: Get all pending tests working

---

app/uk/gov/hmrc/residencenilratebandcalculator/Constants.scala
app/uk/gov/hmrc/residencenilratebandcalculator/Navigator.scala
app/uk/gov/hmrc/residencenilratebandcalculator/json/JsonBuilder.scala
test/uk/gov/hmrc/residencenilratebandcalculator/NavigatorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/json/JsonBuilderSpec.scala

RNRBC-116 & 118: Routing from Estate Has Property and related bug

---

app/uk/gov/hmrc/residencenilratebandcalculator/controllers/CheckAnswersController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/AnswerRow.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/CheckAnswersControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/AnswerRowSpec.scala

Property Value After Exemption requires special formatting

RNRBC-119: Property Value After Exemption requires special formatting

---

app/uk/gov/hmrc/residencenilratebandcalculator/controllers/DBReadTestController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/DBWriteTestController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/repositories/SessionRepository.scala

Change SessionRepository to be dependency injectable

RNRBC-114: Change SessionRepository to be dependency injectable

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/results.scala.html
conf/messages

Remove collision on results.title

RNRBC-120: Remove collision on results.title

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/rnrbHelpers/answer_rows.scala.html
conf/messages
test/uk/gov/hmrc/residencenilratebandcalculator/views/ResultsViewSpec.scala

RNRBC-120: Replace place holders

---

app/uk/gov/hmrc/residencenilratebandcalculator/models/CalculationResult.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/DisplayResults.scala
conf/messages
test/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnectorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ResultsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/DisplayResultsSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ResultsViewSpec.scala

Display the adjusted allowance if different from default

RNRBC-98: Display the adjusted allowance if different from default

---

conf/messages

Make example dates more realistic

RNRBC-128: Make example dates more realistic

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/govuk_wrapper.scala.html
conf/messages

RNRBC-142: Remove service title

---

app/uk/gov/hmrc/residencenilratebandcalculator/Navigator.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyAssetsPassingToDirectDescendantsController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyBroughtForwardAllowanceController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyBroughtForwardAllowanceOnDisposalController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyDownsizingAllowanceController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyExemptionController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyPropertyCloselyInheritedController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/AssetsPassingToDirectDescendantsController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/BroughtForwardAllowanceController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/BroughtForwardAllowanceOnDisposalController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ChargeableTransferAmountController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/DateOfDeathController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/DateOfDisposalController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/EstateHasPropertyController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/GrossEstateValueController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/PercentageCloselyInheritedController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/PropertyValueAfterExemptionController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/PropertyValueController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/PurposeOfUseController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/SimpleControllerBase.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueOfDisposedPropertyController.scala
test/uk/gov/hmrc/residencenilratebandcalculator/NavigatorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyBroughtForwardAllowanceControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AnyDownsizingAllowanceControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/MockSessionConnector.scala

Update back link architecture

---

conf/messages

Update message to reference correct box on 436 form

Update message to reference correct box on 436 form

---

app/uk/gov/hmrc/residencenilratebandcalculator/forms/LargeIntFormatter.scala
app/uk/gov/hmrc/residencenilratebandcalculator/forms/NonNegativeIntForm.scala
app/uk/gov/hmrc/residencenilratebandcalculator/forms/PropertyValueAfterExemptionForm.scala
test/uk/gov/hmrc/residencenilratebandcalculator/forms/LargeIntFormatterSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/forms/NonNegativeIntFormSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/forms/PropertyValueAfterExemptionFormSpec.scala

Allow comma separated integers, such as 20,000

RNRBC-146: Allow comma separated integers, such as 20,000

---

app/uk/gov/hmrc/residencenilratebandcalculator/models/AnswerRow.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/DisplayResults.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/ResultsRow.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ResultsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/ResultsRowSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ResultsViewSpec.scala

Force responses to be localed in GB

RNRBC-147: Force responses to be localed in GB

---

app/uk/gov/hmrc/residencenilratebandcalculator/Constants.scala
app/uk/gov/hmrc/residencenilratebandcalculator/Navigator.scala
app/uk/gov/hmrc/residencenilratebandcalculator/connectors/SessionConnector.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/DoesGrossingUpApplyToOtherPropertyController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/DoesGrossingUpApplyToResidenceController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/AnswerRows.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/UserAnswers.scala
app/uk/gov/hmrc/residencenilratebandcalculator/views/does_grossing_up_apply_to_other_property.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/does_grossing_up_apply_to_residence.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/residencenilratebandcalculator/NavigatorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AssetsPassingToDirectDescendantsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/DoesGrossingUpApplyToOtherPropertyControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/DoesGrossingUpApplyToResidenceControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/PropertyValueAfterExemptionControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/UserAnswersSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/DoesGrossingUpApplyToOtherPropertyViewSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/DoesGrossingUpApplyToResidenceViewSpec.scala

Add the Does Grossing Up Apply To Other Property page

RNRBC-161: Add the Does Grossing Up Apply To Other Property page

---

app/uk/gov/hmrc/residencenilratebandcalculator/Constants.scala
app/uk/gov/hmrc/residencenilratebandcalculator/Navigator.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/CannotClaimRNRBController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/GetCannotClaimRNRBReasonKey.scala
app/uk/gov/hmrc/residencenilratebandcalculator/views/cannot_claim_RNRB.scala.html
conf/app.routes
conf/messages
test/uk/gov/hmrc/residencenilratebandcalculator/NavigatorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/CannotClaimRNRBControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/SimpleControllerSpecBase.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/GetCannotClaimRNRBReasonKeySpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/CannotClaimRNRBViewSpec.scala

RNRBC-236: Add 'Can't Claim RNRB' page

---

app/uk/gov/hmrc/residencenilratebandcalculator/controllers/TransitionOutController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/GetTransitionOutPrefix.scala
app/uk/gov/hmrc/residencenilratebandcalculator/views/not_possible_to_use_service.scala.html
conf/messages
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/TransitionOutControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/GetTransitionOutPrefixSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/NotPossibleToUseServiceViewSpec.scala

Specialise transition out pages

RNRBC-218: Specialise transition out pages

---

app/uk/gov/hmrc/residencenilratebandcalculator/controllers/CannotClaimDownsizingController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/CannotClaimRNRBController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/TransitionController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/TransitionOutController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/GetCannotClaimDownsizingReason.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/GetCannotClaimRNRBReason.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/GetReason.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/GetTransitionOutReason.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/TransitionControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/GetCannotClaimDowisizingReasonKeySpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/GetCannotClaimRNRBReasonKeySpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/GetTransitionOutReasonSpec.scala

Refactor CannotClaim and TransitionOut controllers

RNRBC-290: Refactor CannotClaim and TransitionOut controllers

---

conf/application.conf

Don't know if this will work, but it may do...

RNRBC-433 Missing metrics need to be added to enable memory usage to be assessed

---

app/uk/gov/hmrc/residencenilratebandcalculator/forms/mappings/DateMapping.scala
app/uk/gov/hmrc/residencenilratebandcalculator/frontendAppConfig.scala
conf/messages.cy
conf/messages.en
test/uk/gov/hmrc/residencenilratebandcalculator/forms/DateFormSpec.scala

Can be reviewed but don't merge until the Welsh content for the error messages has been received and integrated.

Rnrbc 465 RNRB - Error display message on date validation

---

app/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnector.scala
app/uk/gov/hmrc/residencenilratebandcalculator/forms/NonNegativeIntForm.scala
app/uk/gov/hmrc/residencenilratebandcalculator/json/JsonErrorProcessor.scala
project/FrontendBuild.scala
test/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnectorSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/json/JsonErrorProcessorSpec.scala

**Bug fix**
Remove a library that was causing build issues and wasn't necessary in the codebase

Remove unnecessary dependency

---

app/uk/gov/hmrc/residencenilratebandcalculator/FrontendAppConfig.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/FeedbackSurveyController.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/FeedbackSurveyControllerSpec.scala

**Bug fix** 
Rectified feedback survey controller and appropriate spec.

to rectify companion object discrepancy

---

project/FrontendBuild.scala

**Maintenance**
Updated all dependencies

DL-1507 Dependency uplift

---

conf/application.conf
project/FrontendBuild.scala
project/plugins.sbt

Dl 1814 - Feedback Survey link update
Feedback survey link change in config. 
Dependency uplift
- []  I've run a dependency check to ensure all dependencies are up to date

Dl 1814 - Feedback Survey link update

---

project/FrontendBuild.scala

Update reactivemongo
- [ x ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
- [ x ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
- [ x ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
- [ x ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
- [ x ]  I've run a dependency check to ensure all dependencies are up to date

Simple reactivemongo updated to 7.20 + dependency updates

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/value_of_assets_passing.scala.html
conf/messages.cy
conf/messages.en

**Bug fix**
Final amendments based on welsh feedback

DL-1774 - Final Welsh messages cleanup

---

build.sbt
project/AppDependencies.scala
project/build.properties

DL-3528 dependency updates

---

app/uk/gov/hmrc/residencenilratebandcalculator/Constants.scala
app/uk/gov/hmrc/residencenilratebandcalculator/FrontendAppConfig.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ChargeableEstateValueController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ChargeableInheritedPropertyValueController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ChargeablePropertyValueController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/FeedbackSurveyController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/IHT435Controller.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/KeepAliveController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/PropertyValueController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/SessionExpiredController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/SimpleControllerBase.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueAvailableWhenPropertyChangedController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueBeingTransferredController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueOfAssetsPassingController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/forms/BooleanForm.scala
app/uk/gov/hmrc/residencenilratebandcalculator/forms/NonNegativeIntForm.scala
app/uk/gov/hmrc/residencenilratebandcalculator/forms/PropertyPassingToDirectDescendantsForm.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/Date.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/GetUnableToCalculateThresholdIncreaseReason.scala
app/uk/gov/hmrc/residencenilratebandcalculator/repositories/SessionRepository.scala
app/uk/gov/hmrc/residencenilratebandcalculator/utils/FormHelpers.scala
build.sbt
project/plugins.sbt
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/DateControllerSpecBase.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/DatePropertyWasChangedControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/IHT435ControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/KeepAliveControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/MockSessionConnector.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueAvailableWhenPropertyChangedControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueBeingTransferredControllerSpec.scala

DL-3563 - Removed compildation and other warnings

---

app/uk/gov/hmrc/residencenilratebandcalculator/repositories/SessionRepository.scala
conf/application.conf
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/TransitionControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueAvailableWhenPropertyChangedControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueBeingTransferredControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/forms/DateFormSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/AnswerRowSpec.scala

DL-3601 removed warnings from unit tests/sbt test

---

conf/application.conf
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/TransitionControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueAvailableWhenPropertyChangedControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueBeingTransferredControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/forms/DateFormSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/models/AnswerRowSpec.scala

DL-3601 reverted sessionRepository.scala to fix jenkins build error

---

project/AppDependencies.scala
project/plugins.sbt

DL-3675 Updating dependencies

---

app/uk/gov/hmrc/residencenilratebandcalculator/utils/RnrbErrorHandler.scala
conf/messages.cy
conf/messages.en
project/AppDependencies.scala

DL-2574 Update to live services generic 500 error message.

---

project/AppDependencies.scala
project/build.properties
project/plugins.sbt

DL-3751 updated ReactiveMongo, SBT and Bootstrap versions

---

conf/logback.xml
conf/messages.cy
conf/messages.en
project/AppDependencies.scala

**Bug fix**
Added Welsh content for when 400's and 404's occur

DL-3780 Welsh for 404's and 400's

---

conf/application.conf
project/AppDependencies.scala

Added a11y statement link to the footer/updated play-ui to 8.12. a11y statement PR: https://github.com/hmrc/accessibility-statement-frontend/pull/166

DL-4234 - A11y statement functionality for RNRB

---

app/uk/gov/hmrc/residencenilratebandcalculator/filters/Filters.scala
conf/application.conf

DL629 - x-request-id header not being passed (filter fix)

---

app/uk/gov/hmrc/residencenilratebandcalculator/controllers/DateOfDeathController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/FeedbackSurveyController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/IHT435Controller.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ThresholdCalculationResultController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueAvailableWhenPropertyChangedController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueBeingTransferredController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/predicates/ValidatedSession.scala
app/uk/gov/hmrc/residencenilratebandcalculator/views/session_expired.scala.html
conf/messages.cy
conf/messages.en
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/DateControllerSpecBase.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/DateOfDeathControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/FeedbackSurveyControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/SimpleControllerSpecBase.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ThresholdCalculationResultControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueAvailableWhenPropertyChangedControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueBeingTransferredControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/SessionExpiredViewSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ValueAvailableWhenPropertyChangedViewSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ValueBeingTransferredViewSpec.scala

DL-5070 Adding redirect for views throwing RuntimeException

---

.bsp/sbt.json
app/uk/gov/hmrc/residencenilratebandcalculator/FrontendAppConfig.scala
app/uk/gov/hmrc/residencenilratebandcalculator/views/govuk_wrapper.scala.html
conf/application.conf

DL-5014 - Added tracking consent and removed GA/GTM code

---

app/uk/gov/hmrc/residencenilratebandcalculator/connectors/RnrbConnector.scala
app/uk/gov/hmrc/residencenilratebandcalculator/connectors/SessionConnector.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/IHT435Controller.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/SessionExpiredController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ThresholdCalculationResultController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueAvailableWhenPropertyChangedController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueBeingTransferredController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/predicates/ValidatedSession.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/CascadeUpsert.scala
app/uk/gov/hmrc/residencenilratebandcalculator/utils/RnrbErrorHandler.scala
project/AppDependencies.scala
project/plugins.sbt

DL-5766 Play 2.8 upgrade

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/claim_downsizing_threshold.scala.html
conf/messages.cy
conf/messages.en

DL-6039 Content change

---

conf/messages.cy
test/uk/gov/hmrc/residencenilratebandcalculator/views/ClaimDownsizingThresholdViewSpec.scala

DL-6039 Fixing unit tests

---

app/uk/gov/hmrc/residencenilratebandcalculator/FrontendAppConfig.scala

DL-6746 added service name to feedback banner

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/Layout.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/calculate_threshold_increase.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/playComponents/heading.scala.html
conf/messages.cy
conf/messages.en
test/uk/gov/hmrc/residencenilratebandcalculator/views/CalculateThresholdIncreaseViewSpec.scala

DL-6971 calculate-additional-inheritance-tax-threshold

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/date_of_death.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/playComponents/input_date_inline.scala.html
conf/messages.cy
conf/messages.en

DL-6972 date-of-death

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/property_passing_to_direct_descendants.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/PropertyPassingToDirectDescendantsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/NewViewSpecBase.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/PropertyPassingToDirectDescendantsViewSpec.scala

Reverts hmrc/residence-nil-rate-band-calculator-frontend#319

Revert "DL-6980 - UI upgrade"

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/playComponents/input_value.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/value_of_estate.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueOfEstateControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/NewIntViewSpecBase.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ValueOfEstateViewSpec.scala

DL-6974 value-of-estate page

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/chargeable_estate_value.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ChargeableEstateValueControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ChargeableEstateValueViewSpec.scala

DL-6975 chargable_estate_value.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/exemptions_and_relief_claimed.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ExemptionsAndReliefClaimedControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ExemptionsAndReliefClaimedViewSpec.scala

DL-6982 exemptions_and_relief_claimed.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/calculate_threshold_increase.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/date_of_death.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/grossing_up_on_estate_property.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/part_of_estate_passing_to_direct_descendants.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/property_in_estate.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/GrossingUpOnEstatePropertyControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/GrossingUpOnEstatePropertyViewSpec.scala

DL-6983 grossing_up_on_estate_property.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/percentage_passed_to_direct_descendants.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/playComponents/input_value.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/PercentagePassedToDirectDescendantsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/NewBigDecimalViewSpecBase.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/PercentagePassedToDirectDescendantsViewSpec.scala

DL-6981 percentage-passed-to-direct-descendants

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/chargeable_inherited_property_value.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ChargeableInheritedPropertyValueControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ChargeableInheritedPropertyValueViewSpec.scala

DL-6986 chargeable-inherited-property-value

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/value_being_transferred.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueBeingTransferredControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ValueBeingTransferredViewSpec.scala

DL-6988 value-being-transferred

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/unable_to_calculate_threshold_increase.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/views/UnableToCalculateThresholdIncreaseViewSpec.scala

DL-6984 unable_to_calculate_threshold_increase.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/transfer_any_unused_threshold.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/TransferAnyUnusedThresholdControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/TransferAnyUnusedThresholdViewSpec.scala

DL-6987 transfer_any_unused_threshold.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/assets_passing_to_direct_descendants.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/AssetsPassingToDirectDescendantsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/AssetsPassingToDirectDescendantsViewSpec.scala

DL-6992 assets-passing-to-direct-descendants

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/chargeable_property_value.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ChargeablePropertyValueControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ChargeablePropertyValueViewSpec.scala

DL-6985 chargeable_property_value.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/value_of_changed_property.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueOfChangedPropertyControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ValueOfChangedPropertyViewSpec.scala

DL-6991 value_of_changed_property.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/value_of_assets_passing.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueOfAssetsPassingControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ValueOfAssetsPassingViewSpec.scala

DL-6998 - value-of-assets-passing

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/no_downsizing_threshold_increase.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/views/NoDownsizingThresholdIncreaseViewSpec.scala

DL-6993 no_downsizing_threshold_increase.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/no_threshold_increase.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/views/NoThresholdIncreaseViewSpec.scala

DL-6996 no_threshold_increase.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/date_property_was_changed.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/views/DatePropertyWasChangedViewSpec.scala

DL-6990 datePropertyWasChanged.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/threshold_calculation_result.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ThresholdCalculationResultControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ThresholdCalculationResultViewSpec.scala

DL-6994 threshold-calculation-result

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/claim_downsizing_threshold.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ClaimDownsizingThresholdControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ClaimDownsizingThresholdViewSpec.scala

DL-6989 claim_downsizing_threshold.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/grossing_up_on_estate_assets.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/GrossingUpOnEstateAssetsControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/GrossingUpOnEstateAssetsViewSpec.scala

DL-6997 grossing_up_on_estate_assets.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/transfer_available_when_property_changed.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/TransferAvailableWhenPropertyChangedControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/TransferAvailableWhenPropertyChangedViewSpec.scala

DL-7077 transfer_available_when_property_changed.scala.html

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/value_available_when_property_changed.scala.html
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ValueAvailableWhenPropertyChangedControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ValueAvailableWhenPropertyChangedViewSpec.scala

DL-7078 value_available_when_property_changed.scala.html

---

conf/prod.routes
project/AppDependencies.scala

DL-7061 remove play-ui

---

.bsp/sbt.json
.gitignore
app/uk/gov/hmrc/residencenilratebandcalculator/views/Layout.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/calculate_threshold_increase.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/date_of_death.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/date_property_was_changed.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/exemptions_and_relief_claimed.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/playComponents/answer_rows.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/playComponents/button_link.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/playComponents/error_summary.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/property_passing_to_direct_descendants.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/session_expired.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/threshold_calculation_result.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/unable_to_calculate_threshold_increase.scala.html
conf/application.conf
test/uk/gov/hmrc/residencenilratebandcalculator/views/SessionExpiredViewSpec.scala

DL-7064 - Manually inspect each page

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/threshold_calculation_result.scala.html
conf/messages.en

DL-7194 replace inset text with govuk-body

---

conf/messages.en

DL-7236 - Removed additional full stop

---

conf/messages.en

DL-7301 - Changed 'IHT 345' to 'IHT 435'

---

app/uk/gov/hmrc/residencenilratebandcalculator/repositories/SessionRepository.scala

Changed SessionRepository's json format to populate the `lastUpdated` field with a `Date` type value instead of a string. Tested locally with Robo 3T:

DL-8433 - Changed session json format

---

app/uk/gov/hmrc/residencenilratebandcalculator/repositories/SessionRepository.scala

Included task which corrects the invalid type of SessionRepository mongo documents (specifically the `lastUpdated` field) so that they can be cleared down via TTL.
Will revert this PR once the documents have been corrected in production.

DL-8433 - Added update task

---

app/uk/gov/hmrc/residencenilratebandcalculator/repositories/SessionRepository.scala

The task to convert the invalid mongo documents has ran. Removing task

Revert "DL-8433 - Added update task"

---

README.md

DL-9885 update READ.me file

---

app/uk/gov/hmrc/residencenilratebandcalculator/controllers/NoAdditionalThresholdAvailableController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/NoDownsizingThresholdIncreaseController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/NoThresholdIncreaseController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/controllers/UnableToCalculateThresholdIncreaseController.scala
app/uk/gov/hmrc/residencenilratebandcalculator/models/CalculationInput.scala
app/uk/gov/hmrc/residencenilratebandcalculator/repositories/SessionRepository.scala
project/AppDependencies.scala

DL-10169 Dependency updates

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/calculate_threshold_increase.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/threshold_calculation_result.scala.html
conf/messages.cy
conf/messages.en
test/uk/gov/hmrc/residencenilratebandcalculator/controllers/ThresholdCalculationResultControllerSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/CalculateThresholdIncreaseViewSpec.scala
test/uk/gov/hmrc/residencenilratebandcalculator/views/ThresholdCalculationResultViewSpec.scala

DL-11223 align title with h1

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/threshold_calculation_result.scala.html

DL-11233 fixing govuk-links on calculation page

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/assets_passing_to_direct_descendants.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/claim_downsizing_threshold.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/exemptions_and_relief_claimed.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/grossing_up_on_estate_assets.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/grossing_up_on_estate_property.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/part_of_estate_passing_to_direct_descendants.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/property_in_estate.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/transfer_any_unused_threshold.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/transfer_available_when_property_changed.scala.html

DL-11224 remove h1 from radio label

---

conf/messages.cy
conf/messages.en

DL-11225 error message changes

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/value_of_estate.scala.html

add class to link to fix link accessibility

---

app/assets/javascripts/print.js
app/uk/gov/hmrc/residencenilratebandcalculator/views/Layout.scala.html
app/uk/gov/hmrc/residencenilratebandcalculator/views/threshold_calculation_result.scala.html
conf/application.conf
project/AppDependencies.scala

DL-11776 remove csp directive

---

app/uk/gov/hmrc/residencenilratebandcalculator/views/Layout.scala.html
conf/application.conf
project/plugins.sbt

DL-11948 changing to hmrcStandardPage

---

conf/messages.cy
conf/messages.en

DL-12071 fix error page title

---

project/AppDependencies.scala

DL-12313 update play-frontend-hmrc version

---

project/AppDependencies.scala

DL-12979 update crown logo

---

project/AppDependencies.scala

DL-15298:Rectify bobby violation

DL-15298:Rectify bobby violation

---

README.md
project/AppDependencies.scala

DL-15309: Updated readme and Upgraded the appDependencies
